version: '3'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=s3cret
      - MYSQL_DATABASE=satisfyingDB
